Repository writefreely/writefreely, pull requests merged in 2020-03, with the labels that each got.

#264 Admin dashboard redesign
  admin.go
  config/config.go
  less/admin.less
  less/core.less
  routes.go
  templates/user/admin.tmpl
  templates/user/admin/app-settings.tmpl
  templates/user/admin/app-updates.tmpl
  templates/user/admin/monitor.tmpl
  templates/user/admin/users.tmpl
  templates/user/admin/view-user.tmpl
  templates/user/include/header.tmpl
  updates.go
  updates_test.go
Labels: design

#267 Update Contributing guide
  CONTRIBUTING.md
Labels: help wanted

#263 Typography Improvements, Vol. I
  less/core.less
  less/new-core.less
  less/post-temp.less
Labels: design

#194 lightly style tables in posts
  less/core.less
Labels: design

#281 Accessibility improvements for readers
  less/new-core.less
  less/post-temp.less
Labels: accessbility, design
